
; You may customize this and other start-up templates; 
; The location of this template is c:\emu8086\inc\0_com_template.txt

org 100h

.DATA
    ; operator stack
    OP_STACK_SIZE EQU 50
    OP_STACK DB OP_STACK_SIZE DUP(?)
    OP_STACK_PTR DW 0  ; operator stack pointer

    ; operand stack
    VAL_STACK_SIZE EQU 50
    VAL_STACK DW VAL_STACK_SIZE DUP(?) 
    VAL_STACK_PTR DW 0  ; operand stack pointer 
    
    ; buffer for input string
    BUFFER_SIZE DB 51
    ACTUAL_LEN  DB ?
    INPUT_STR   DB 50 DUP(?)
    
    ; COUNTER FOR READING THE STRING 
    COUNTER DB 0
    
    ; a charecter for new line( for print the result )
    NEWLINE     DB 0Dh, 0Ah, '$'  
    
    ; OUTPUT MASSAGE AND OUTPUT BUFFER
    RESULT_MSG  DB 'RESULT = $'
    OUTPUT_BUF  DB 6 DUP('$')   
    
    ; A MASSAGE FOR INVALID CHARECTER
    ERROR_INVALID_CHAR_MSG DB 'Error: Invalid Character Found!$' 
    
    ; A MASSAGE FOR DIV BY ZERO
    DIV_ERR_MSG DB 'Error: Division by zero is undefined!$'  
    
    ; A MASSAGE FOR UNBALANCED PAREN
    PAREN_ERR_MSG DB 'Error: Unbalanced Parentheses!$'
    
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    ; --- get input ---
    CALL GET_INPUT 
    
    ; --- CONVERT INFIX INTO POSTFIX ---
    CALL PROCESS_EXPRESSION    
    
    ; --- CACULATE FINALL RESULT ---
    CALL FINALIZE_CALCULATION

    ; --- PRINT NEW CHARECTER FOR PRINT RESULT IN NEXT LINE ---
    CALL PRINT_NEW_LINE 
                        
    ; --- PRINT THE RESULT ---
    CALL PRINT_RESULT                    
                        
    ; --- PRINT THE INPUT ( FOR TEST ) ---
    ;CALL PRINT_STRING 
    
MAIN ENDP 

; ---FUNCTIONS---    

;1. --- get input ---
GET_INPUT PROC
    LEA DX, BUFFER_SIZE    ; DX = BUFFER ADDRESS 
    MOV AH, 0Ah            
    INT 21h                ; INTRUPT 
    RET
GET_INPUT ENDP  

;2. --- PRINT NEW LINE ---
PRINT_NEW_LINE PROC
    LEA DX, NEWLINE
    MOV AH, 09h
    INT 21h
    RET
PRINT_NEW_LINE ENDP  

;3. --- PRINT RESULT ---
;PRINT_STRING PROC
 ;   MOV BL, ACTUAL_LEN     ; THE NUMBER OF INPUT CHARECTERS
  ;  MOV BH, 0
   ; MOV INPUT_STR[BX], '$' 

   ; LEA DX, INPUT_STR      ; PRINT
   ; MOV AH, 09h
   ; INT 21h

   ; MOV AH, 4Ch            ; GET OUT OF PROGRAM
   ; INT 21h
   ; RET
;PRINT_STRING ENDP

;4. --- CONVERT INFIX TO POSTFIX ---
PROCESS_EXPRESSION PROC
    LEA SI, INPUT_STR    ; SI = POINT TO THE FIRST CHARECTER IN THE INPUT STRING
    
LOOP_START:
    MOV AL, [SI]         ; AL = THE ACTUALY CHARECTER   
    
    MOV BL, COUNTER   
    MOV CL, ACTUAL_LEN
    CMP BL, CL          ; IS IT THE STRING FINISHED?
    JE END_PROCESS
    
    ; CHECK THAT IT IS NUMBER OR NOT
    CMP AL, '0'
    JB CHECK_OP    
    CMP AL, '9'
    JA CHECK_OP    
    
    ; IF THE CHARECTER IS A NUMBER
    CALL PARSE_NUMBER   
    MOV AL, COUNTER   
    INC AL            
    MOV COUNTER, AL
    JMP LOOP_START
    
;NEXT_CHAR:
    ;INC SI               ; GO TO THE NEXT CHARECTER
    ;JMP LOOP_START

CHECK_OP:
    CALL CHECK_OPERATOR
    MOV AL, COUNTER   
    INC AL            
    MOV COUNTER, AL
    JMP LOOP_START
    
END_PROCESS:
    RET
PROCESS_EXPRESSION ENDP

;5. --- PUSH THE OPERATOR IN THE OPERATOR STACK ---
PUSH_OP PROC
    MOV BX, OP_STACK_PTR
    MOV OP_STACK[BX], AL ; PUSH THE OPERATOR ( ONE BYTE )
    INC OP_STACK_PTR     ; UPDATE THE OPERATOR STACK POINTER
    RET
PUSH_OP ENDP

;6. --- PUSH THE OPERAND IN THE OPERAND STACK ---
PUSH_VAL PROC
    MOV BX, VAL_STACK_PTR
    MOV VAL_STACK[BX], AX ; PUSH THE NUMBER ( ONE WORD )
    ADD VAL_STACK_PTR, 2  ; UPDATE THE OPERAND STACK POINTER
    RET
PUSH_VAL ENDP  

;7. --- CHECK THE OPERATOR ---
CHECK_OPERATOR PROC
    
    CMP AL, '('
    JE IS_OPERATOR
    
    CMP AL, ')'
    JE IS_CLOSE_PAREN
    
    CMP AL, '+'
    JE IS_OPERATOR
    
    CMP AL, '-'
    JE IS_OPERATOR
    
    CMP AL, '*'
    JE IS_OPERATOR
    
    CMP AL, '/'
    JE IS_OPERATOR
    
    JMP INVALID_CHARECTER

IS_CLOSE_PAREN:
    CALL HANDLE_CLOSE_PAREN 
    INC SI
    RET

IS_OPERATOR:   
    CALL PROCESS_OPERATOR 
    INC SI
    RET

INVALID_CHARECTER:
    CALL PRINT_NEW_LINE 
    CALL INVALID_CHAR
    
CHECK_OPERATOR ENDP  
    
;8. --- PARSE NUMBER ---
; INPUT: SI = POINT TO THE FIRST DIGIT
; OUTPUT: AX = THE FULL NUMBER ( INTEGER FORMAT ) , SI = POINT TO THE FIST CHARECTER AFTER THE NUMBER
PARSE_NUMBER PROC
    XOR AX, AX       ; AX = 0
    MOV CX, 10       
    
NEXT_DIGIT:
    MOV BL, [SI]     ; READ THE CHARECTER ==> BL = THE CHARECTER
     
    ; THE CHARECTER IS STILL A DIGIT OR NOT
    CMP BL, '0'
    JB FINISH_NUMBER 
    CMP BL, '9'
    JA FINISH_NUMBER 
     
    ; CONVERT THE CHARECTER INTO THE DIGIT
    SUB BL, '0'
    
    ; AX = AX * 10
    PUSH DX          
    MUL CX           
    POP DX
    
    ; AX = AX + NEW DIGIT
    MOV BH, 0
    ADD AX, BX       
    
    INC SI           
    JMP NEXT_DIGIT

FINISH_NUMBER:
    ; NOW SI POINT TO THE OPERATOR AFTER THE NUMBER
    ; PUSH THE AX INTO THE STACK
    CALL PUSH_VAL    
    RET
PARSE_NUMBER ENDP  

;9. --- DO MULTIPLY ---
MUL_OP PROC
    MUL BX                 
    RET
MUL_OP ENDP  

;10. --- DO DIVISION ---
DIV_OP PROC
    
    CMP AX, 0
    JE DIV_BY_ZERO_ERROR
    
    XCHG AX, BX      
    XOR DX, DX       
    DIV BX                     
    RET
DIV_BY_ZERO_ERROR: 
 
    CALL PRINT_NEW_LINE 
    LEA DX, DIV_ERR_MSG
    MOV AH, 09H
    INT 21H

    MOV AH, 4CH
    INT 21H
    
DIV_OP ENDP   

;11. --- DO ADD ---
ADD_OP PROC
    ADD AX, BX                
    RET
ADD_OP ENDP 

;12.--- DO SUB ---
SUB_OP PROC
    ;XCHG AX, BX      
    SUB BX, AX
    MOV AX, BX                
    RET
SUB_OP ENDP  

;13. --- process a new operator before pushing it ---
; input: AL = NEW OPERATOR
PROCESS_OPERATOR PROC
    ; IF THE STACK OF OPERATORS ARE EMPTY JUST PUSH THE NEW OPERATOR
    CMP OP_STACK_PTR, 0
    JE PUSH_TO_STACK

    ; COMPARE THE PRIORITY ( CL = NEW OPERATOR PRIORITY , BL = THE TOP OF STACK OPERATOR PRIORITY )
    CALL GET_PRECEDENCE  
    MOV CL, BL
    
    MOV BX, OP_STACK_PTR
    DEC BX
    MOV AH, OP_STACK[BX]    ; AH = THE TOP OPERATOR IN THE STACK
    
    PUSH AX                 ; SAVE THE AL
    MOV AL, AH
    CALL GET_PRECEDENCE     
    POP AX            
    
    ; IF THE TOP OPERATOR ON THE OPERATOR STACK IS AN OPEN PAREN
    CMP BL, 3          
    JE PUSH_TO_STACK     
    
    ; IF CL > BL
    CMP CL, BL              
    JA PUSH_TO_STACK        

    ; IF CL <= BL
    ;POP THE TOP OPERATOR IN STACK
    POP_OP:  
        PUSH AX
        MOV BX, OP_STACK_PTR
        DEC BX
        MOV AL, OP_STACK[BX] ; THE TOP OPERATOR IN STACK FOR CACULATE
        DEC OP_STACK_PTR
        
        ; DO THE TOP OPERATOE PROCESS
        CALL EXECUTE_OP  
        POP AX
        JMP CONTINUE_CHECK

CONTINUE_CHECK:
    CMP OP_STACK_PTR, 0  
    JNE PROCESS_OPERATOR

PUSH_TO_STACK:
    CALL PUSH_OP
    RET
PROCESS_OPERATOR ENDP

;14. --- CACULATE THE OPERATOR PRIORITY ---
; INPUT: AL = THE OPERATOR
; OUTPUT: BL = THE PRIORITY OF THE OPERATOR
GET_PRECEDENCE PROC
    CMP AL, '('
    JE PREC_HIGH    
    
    CMP AL, '*'
    JE PREC_MUL
    CMP AL, '/'
    JE PREC_MUL
    
    CMP AL, '+'
    JE PREC_ADD
    CMP AL, '-'
    JE PREC_ADD
    
    MOV BL, 0       ; FOR NOT OPERATORS
    RET

PREC_HIGH: 
    MOV BL, 3
    RET
PREC_MUL:  
    MOV BL, 2
    RET
PREC_ADD:  
    MOV BL, 1
    RET
GET_PRECEDENCE ENDP 

;15. --- HANDLE THE CLOSE PAREN ---
; THIS FUNCTION RUNING UNTILL SEA THE OPEN PAREN
HANDLE_CLOSE_PAREN PROC
LOOP_POP_UNTIL_OPEN:
    ; CHECK IF STACK IS EMPTY
    CMP OP_STACK_PTR, 0
    JE ERROR_UNBALANCED

    ; POP THE OPERATOR FROM OPERATOR STACK
    DEC OP_STACK_PTR
    MOV BX, OP_STACK_PTR
    MOV AL, OP_STACK[BX]

    ; IS THE OPERATOR IS OPEN PAREN?
    CMP AL, '('
    JE DONE_PAREN     ; RUNING THIS FUNCTION IS DONE

    ; IF THE OPERATOR IS NOT OPEN PAREN , DO THE PROCESS
    
    CALL EXECUTE_OP   
    JMP LOOP_POP_UNTIL_OPEN

ERROR_UNBALANCED:
    
    CALL ERROR_UNBALANCED_PAREN 
    

DONE_PAREN:
    RET
HANDLE_CLOSE_PAREN ENDP 

;16. --- DO THE CACULATES ---
EXECUTE_OP PROC 
    MOV CL, AL 
    
    ; POP TWO TOP OF OPERANDS IN OPERANDS STACK  
    SUB VAL_STACK_PTR, 2
    MOV BX, VAL_STACK_PTR
    MOV AX, VAL_STACK[BX] ; THE SECEND OPERAND
    SUB VAL_STACK_PTR, 2  
    MOV BX, VAL_STACK_PTR
    MOV BX, VAL_STACK[BX] ; THE FIRST OPERAND
        
    
    CMP CL, '+'
    JE DO_ADD
    CMP CL, '-'
    JE DO_SUB
    CMP CL, '*'
    JE DO_MUL
    CMP CL, '/'
    JE DO_DIV  
DO_ADD:
    CALL ADD_OP
    JMP END_CALC

DO_SUB:
    CALL SUB_OP
    JMP END_CALC

DO_MUL:
    CALL MUL_OP
    JMP END_CALC

DO_DIV:
    CALL DIV_OP
    JMP END_CALC  

END_CALC:
    MOV BX, VAL_STACK_PTR    
    MOV VAL_STACK[BX], AX    ; PUSH THE RESULT IN OPERAND STACK
    ADD VAL_STACK_PTR, 2     
    RET
EXECUTE_OP ENDP

;17. --- THE FINALL CACULATE FOR THE FINALL ANSWER ---
FINALIZE_CALCULATION PROC
    
CHECK_STACK_LOOP:
    ; CHECK THAT THE OPERATOR STACK IS EMPTY OR NOT
    CMP OP_STACK_PTR, 0
    JE FINAL_RESULT_READY    ; IF THE OPERATOR STACK IS EMPTY ==> FINALL RESULT IS READY
    
    
    ; POP THE OPERATORS FROM THE OPERATOR STACK
    DEC OP_STACK_PTR
    MOV BX, OP_STACK_PTR
    MOV AL, OP_STACK[BX]     ; AL = THE TOP OPERATOR OF OPERATOR STACK
    
    CMP AL, '('
    JE CALL ERROR_UNBALANCED_PAREN 
    
    ; DO THE CACULATE 
    CALL EXECUTE_OP
    
    
    
    JMP CHECK_STACK_LOOP     ; DO THIS LOOP UNTILL THE OPERATOR STACK GET EMPTY

FINAL_RESULT_READY:
    ; FINALL RESULT IS IN VAL_STACK[0]
    RET
FINALIZE_CALCULATION ENDP    

;18. --- GET THE RESULT AND PRINT IT ---
PRINT_RESULT PROC
    ; PRINT ' RESULT = '
    LEA DX, RESULT_MSG
    MOV AH, 09H
    INT 21H

    ; GET THE RESULT FROM THE OPERAND STACK
    MOV AX, VAL_STACK[0]
    
    ; CONVERT THE NUMBER INTO A STRING
    MOV CX, 0        ; THE COUNTER
    MOV BX, 10       

CONVERT_LOOP:
    XOR DX, DX       ; DX = 0
    DIV BX           ; AX = AX / 10 , DX = THE REMINDER DIGITS
    PUSH DX          ; SAVE THE DIGIT IN SYSTEM STACK
    INC CX           ; INCREASE THE COUNTER
    CMP AX, 0
    JNE CONVERT_LOOP ; IF AX != 0 THEN CONTINIU

PRINT_LOOP:
    POP DX           ; GET THE DIGIT FROM SYSTEM STACK
    ADD DL, '0'      ; CONVERT THE DIGIT INTO ASCII CODE
    MOV AH, 02H      ; PRINT THE CHARECTER
    INT 21H
    LOOP PRINT_LOOP  ; REPEAT IT FOR ALL DIGITS

    RET
PRINT_RESULT ENDP

;19. --- INVALID CHARECTER ERROR ---
INVALID_CHAR PROC
    
    LEA DX, ERROR_INVALID_CHAR_MSG      
    MOV AH, 09H            
    INT 21H

    
    MOV AH, 4CH            
    INT 21H
INVALID_CHAR ENDP

;20. --- UNBALANCED PAREN ---
ERROR_UNBALANCED_PAREN PROC 
    CALL PRINT_NEW_LINE
    LEA DX, PAREN_ERR_MSG
    MOV AH, 09H
    INT 21H

    
    MOV AH, 4CH
    INT 21H
ERROR_UNBALANCED_PAREN ENDP    
    

END MAIN    

ret




